include: package:lint/analysis_options_package.yaml

linter:
  rules:
    prefer_single_quotes: true
    sort_constructors_first: true

analyzer:
  exclude:
    - "lib/generated/**/*.dart"
    - "**/*.g.dart"
