name: eh_redux
description: EH Redux
publish_to: 'none'
version: 0.3.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  html: ^0.14.0+3
  cached_network_image: ^2.2.0+1
  built_collection: ^4.3.2
  provider: ^4.1.2
  meta: ^1.1.8
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  built_value: ^7.1.0
  share: ">=0.6.4+3 <2.0.0"
  photo_view: ^0.9.2
  shared_preferences: ">=0.5.7+3 <2.0.0"
  preload_page_view: ^0.1.4
  collection: ^1.14.12
  flutter_secure_storage: ^3.3.3
  webview_flutter: ^0.3.22+1
  package_info: ">=0.4.1 <2.0.0"
  url_launcher: ^5.4.10
  filesize: ^1.0.4
  intl: ^0.16.1
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.15
  firebase_crashlytics: ^0.1.3+3
  flutter_markdown: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.5
  mobx_codegen: ^1.1.0
  built_value_generator: ^7.1.0
  lint: ^1.0.0

flutter:
  uses-material-design: true
