name: ehreader
description: E-Hentai Reader
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  html: ^0.14.0+3
  cached_network_image: ^2.2.0+1
  built_collection: ^4.3.2
  provider: ^4.1.2
  meta: ^1.1.8
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  built_value: ^7.1.0
  share: ^0.6.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.5
  mobx_codegen: ^1.1.0
  built_value_generator: ^7.1.0
  lint: ^1.0.0

flutter:
  uses-material-design: true
